export const products = [
  {
    title: 'Title Product 1',
    _id: 'Title Product 1',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi ducimus velit, architecto aut et aspernatur. Aliquid veniam atque dolorum omnis, temporibus dicta? Excepturi eveniet, odio perspiciatis doloribus placeat assumenda? Iure ea voluptas ex! Porro, ex. Sequi, in. Sed quis laborum accusamus ipsam tempore provident impedit blanditiis aut, nihil, delectus iure unde! At provident, assumenda impedit ducimus perferendis eos! Id quaerat laudantium nobis libero. Facere maiores enim eligendi beatae consectetur neque sit nesciunt quaerat dignissimos harum? Sed quia eius, fugit cum numquam explicabo tenetur atque, odio autem rem vitae, officia optio! Optio, vel ipsa animi magnam omnis, sunt expedita magni temporibus sint enim rerum, quas repellat non commodi nesciunt. Eligendi minima repudiandae cupiditate atque nostrum sint ea maiores. Ipsam officiis velit doloribus aspernatur vero cum, fugit harum provident libero eum, laboriosam atque cupiditate omnis, tempora mollitia ea et delectus illum expedita sed repudiandae. Ducimus similique iusto et nam fugiat asperiores modi mollitia eos, sit quasi porro aut ab dolorum quam nesciunt error blanditiis commodi animi amet. Dolorem commodi explicabo harum autem reiciendis distinctio omnis repudiandae amet, quisquam consequatur rerum, non expedita quia illo mollitia culpa? Ea ex, veniam eveniet iusto assumenda omnis consequatur tempore atque doloremque obcaecati voluptates animi vero impedit!',
    price: 34,
    discount: 12,
    slug: 'title-product-1',
    rating: 3.2,
    ratingCount: 10,
    category: 'test',
    imageUrl: require('../assets/uploads/1.jpg'),
  },
  {
    title: 'Title Product 2',
    _id: 'Title Product 2',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi ducimus velit, architecto aut et aspernatur. Aliquid veniam atque dolorum omnis, temporibus dicta? Excepturi eveniet, odio perspiciatis doloribus placeat assumenda? Iure ea voluptas ex! Porro, ex. Sequi, in. Sed quis laborum accusamus ipsam tempore provident impedit blanditiis aut, nihil, delectus iure unde! At provident, assumenda impedit ducimus perferendis eos! Id quaerat laudantium nobis libero. Facere maiores enim eligendi beatae consectetur neque sit nesciunt quaerat dignissimos harum? Sed quia eius, fugit cum numquam explicabo tenetur atque, odio autem rem vitae, officia optio! Optio, vel ipsa animi magnam omnis, sunt expedita magni temporibus sint enim rerum, quas repellat non commodi nesciunt. Eligendi minima repudiandae cupiditate atque nostrum sint ea maiores. Ipsam officiis velit doloribus aspernatur vero cum, fugit harum provident libero eum, laboriosam atque cupiditate omnis, tempora mollitia ea et delectus illum expedita sed repudiandae. Ducimus similique iusto et nam fugiat asperiores modi mollitia eos, sit quasi porro aut ab dolorum quam nesciunt error blanditiis commodi animi amet. Dolorem commodi explicabo harum autem reiciendis distinctio omnis repudiandae amet, quisquam consequatur rerum, non expedita quia illo mollitia culpa? Ea ex, veniam eveniet iusto assumenda omnis consequatur tempore atque doloremque obcaecati voluptates animi vero impedit!',
    price: 12,
    discount: 0,
    slug: 'title-product-2',
    rating: 2,
    ratingCount: 10,
    category: 'category 2',
    imageUrl: require('../assets/uploads/1.jpg'),
  },
  {
    title: 'Title Product 3',
    _id: 'Title Product 3',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi ducimus velit, architecto aut et aspernatur. Aliquid veniam atque dolorum omnis, temporibus dicta? Excepturi eveniet, odio perspiciatis doloribus placeat assumenda? Iure ea voluptas ex! Porro, ex. Sequi, in. Sed quis laborum accusamus ipsam tempore provident impedit blanditiis aut, nihil, delectus iure unde! At provident, assumenda impedit ducimus perferendis eos! Id quaerat laudantium nobis libero. Facere maiores enim eligendi beatae consectetur neque sit nesciunt quaerat dignissimos harum? Sed quia eius, fugit cum numquam explicabo tenetur atque, odio autem rem vitae, officia optio! Optio, vel ipsa animi magnam omnis, sunt expedita magni temporibus sint enim rerum, quas repellat non commodi nesciunt. Eligendi minima repudiandae cupiditate atque nostrum sint ea maiores. Ipsam officiis velit doloribus aspernatur vero cum, fugit harum provident libero eum, laboriosam atque cupiditate omnis, tempora mollitia ea et delectus illum expedita sed repudiandae. Ducimus similique iusto et nam fugiat asperiores modi mollitia eos, sit quasi porro aut ab dolorum quam nesciunt error blanditiis commodi animi amet. Dolorem commodi explicabo harum autem reiciendis distinctio omnis repudiandae amet, quisquam consequatur rerum, non expedita quia illo mollitia culpa? Ea ex, veniam eveniet iusto assumenda omnis consequatur tempore atque doloremque obcaecati voluptates animi vero impedit!',
    price: 99.99,
    discount: 0,
    slug: 'title-product-3',
    rating: 4.9,
    ratingCount: 10,
    category: 'category',
    imageUrl: require('../assets/uploads/1.jpg'),
  },
  {
    title: 'Title Product 4',
    _id: 'Title Product 4',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi ducimus velit, architecto aut et aspernatur. Aliquid veniam atque dolorum omnis, temporibus dicta? Excepturi eveniet, odio perspiciatis doloribus placeat assumenda? Iure ea voluptas ex! Porro, ex. Sequi, in. Sed quis laborum accusamus ipsam tempore provident impedit blanditiis aut, nihil, delectus iure unde! At provident, assumenda impedit ducimus perferendis eos! Id quaerat laudantium nobis libero. Facere maiores enim eligendi beatae consectetur neque sit nesciunt quaerat dignissimos harum? Sed quia eius, fugit cum numquam explicabo tenetur atque, odio autem rem vitae, officia optio! Optio, vel ipsa animi magnam omnis, sunt expedita magni temporibus sint enim rerum, quas repellat non commodi nesciunt. Eligendi minima repudiandae cupiditate atque nostrum sint ea maiores. Ipsam officiis velit doloribus aspernatur vero cum, fugit harum provident libero eum, laboriosam atque cupiditate omnis, tempora mollitia ea et delectus illum expedita sed repudiandae. Ducimus similique iusto et nam fugiat asperiores modi mollitia eos, sit quasi porro aut ab dolorum quam nesciunt error blanditiis commodi animi amet. Dolorem commodi explicabo harum autem reiciendis distinctio omnis repudiandae amet, quisquam consequatur rerum, non expedita quia illo mollitia culpa? Ea ex, veniam eveniet iusto assumenda omnis consequatur tempore atque doloremque obcaecati voluptates animi vero impedit!',
    price: 59.99,
    discount: 23,
    slug: 'title-product',
    rating: 3.6,
    ratingCount: 10,
    category: 'category',
    imageUrl: require('../assets/uploads/1.jpg'),
  },
  {
    title: 'Title Product 5 ',
    _id: 'Title Product 5',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi ducimus velit, architecto aut et aspernatur. Aliquid veniam atque dolorum omnis, temporibus dicta? Excepturi eveniet, odio perspiciatis doloribus placeat assumenda? Iure ea voluptas ex! Porro, ex. Sequi, in. Sed quis laborum accusamus ipsam tempore provident impedit blanditiis aut, nihil, delectus iure unde! At provident, assumenda impedit ducimus perferendis eos! Id quaerat laudantium nobis libero. Facere maiores enim eligendi beatae consectetur neque sit nesciunt quaerat dignissimos harum? Sed quia eius, fugit cum numquam explicabo tenetur atque, odio autem rem vitae, officia optio! Optio, vel ipsa animi magnam omnis, sunt expedita magni temporibus sint enim rerum, quas repellat non commodi nesciunt. Eligendi minima repudiandae cupiditate atque nostrum sint ea maiores. Ipsam officiis velit doloribus aspernatur vero cum, fugit harum provident libero eum, laboriosam atque cupiditate omnis, tempora mollitia ea et delectus illum expedita sed repudiandae. Ducimus similique iusto et nam fugiat asperiores modi mollitia eos, sit quasi porro aut ab dolorum quam nesciunt error blanditiis commodi animi amet. Dolorem commodi explicabo harum autem reiciendis distinctio omnis repudiandae amet, quisquam consequatur rerum, non expedita quia illo mollitia culpa? Ea ex, veniam eveniet iusto assumenda omnis consequatur tempore atque doloremque obcaecati voluptates animi vero impedit!',
    price: 234,
    discount: 20,
    slug: 'title-product-5',
    rating: 5,
    ratingCount: 10,
    category: 'test',
    imageUrl: require('../assets/uploads/1.jpg'),
  },
];
